[project]
name = "repl-nix-nekoregist"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.35.70",
    "gradio>=5.3.0",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.36",
]
